version: '3.9'

services:
  s1:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - ./gems:/usr/local/bundle
    command: bash -c "bundle install && ruby server_1.rb"
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "4001:4001"
    depends_on:
      - redis
      - postgres-proj
  s2:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - ./gems:/usr/local/bundle
    command: bash -c "bundle install && ruby server_2.rb"
    ports:
      - "4002:4002"
    depends_on:
      - redis
      - postgres-proj
  s3:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - ./gems:/usr/local/bundle
    command: bash -c "bundle install && ruby server_3.rb"
    ports:
      - "4003:4003"
    depends_on:
      - redis
      - postgres-proj
  s4:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - ./gems:/usr/local/bundle
    command: bash -c "bundle install && ruby server_4.rb"
    ports:
      - "4004:4004"
    depends_on:
      - redis
      - postgres-proj
  postgres-proj:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data-rebase-labs:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
  sidekiq:
    image: ruby
    container_name: sidekiq
    working_dir: /app
    volumes:
      - .:/app
      - ./gems:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379/0
    command: bash -c "bundle exec sidekiq -r ./public/feature_4/csv_importer.rb"
    depends_on:
      - redis





